# Generated by Django 3.2.2 on 2021-05-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
